apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zama-jobs

resources:
  - namespace.yaml
  - nats-deployment.yaml
  - job-handler-deployment.yaml
  - job-processor-deployment.yaml

commonLabels:
  project: zama-jobs
  environment: base

images:
  - name: job-handler
    newName: katson360/zama-job-handler
    newTag: latest
  - name: job-processor
    newName: katson360/zama-job-processor
    newTag: latest