apiVersion: v1
kind: Namespace
metadata:
  name: zama-system
  labels:
    name: zama-system
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
  labels:
    name: kong
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: iam
  labels:
    name: iam
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: messaging
  labels:
    name: messaging
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    pod-security.kubernetes.io/enforce: baseline