image:
  repository: kong
  tag: "3.4"

env:
  database: "off"
  nginx_worker_processes: "2"
  proxy_access_log: /dev/stdout
  admin_access_log: /dev/stdout
  admin_gui_access_log: /dev/stdout
  portal_api_access_log: /dev/stdout

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001

proxy:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

enterprise:
  enabled: false
