apiVersion: v1
kind: Secret
metadata:
  name: blockchain-secret
  namespace: zama-system
type: Opaque
stringData:
  private-key: "0x0000000000000000000000000000000000000000000000000000000000000001"
  rpc-url: "https://polygon-mumbai.g.alchemy.com/v2/demo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-config
  namespace: zama-system
data:
  config.yaml: |
    blockchain:
      network: polygon-mumbai
      chain_id: 80001
      contract_address: "0x0000000000000000000000000000000000000000"
      confirmations_required: 3
      gas_limit: 500000
      gas_price_gwei: 30

    database:
      host: postgres.storage.svc.cluster.local
      port: 5432
      database: zama_jobs
      username: zama
      password: zama123

    nats:
      url: nats://blockchain-service:blockchain123@nats-client.messaging.svc.cluster.local:4222

    server:
      port: 8080
      timeout: 30s

    monitoring:
      enabled: true
      interval: 30s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
  namespace: zama-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain-service
      tier: blockchain
  template:
    metadata:
      labels:
        app: blockchain-service
        tier: blockchain
    spec:
      containers:
      - name: service
        image: zama/blockchain-service:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: CONFIG_PATH
          value: /etc/config/config.yaml
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: blockchain-secret
              key: private-key
        - name: RPC_URL
          valueFrom:
            secretKeyRef:
              name: blockchain-secret
              key: rpc-url
        volumeMounts:
        - name: config
          mountPath: /etc/config
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: blockchain-config
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  namespace: zama-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: blockchain-service