apiVersion: v1
kind: ConfigMap
metadata:
  name: job-submission-config
  namespace: zama-system
data:
  config.yaml: |
    server:
      port: 8080
      host: "0.0.0.0"

    database:
      host: postgres.storage.svc.cluster.local
      port: 5432
      database: zama_jobs
      username: zama
      password: zama123
      max_connections: 20

    redis:
      host: redis.storage.svc.cluster.local
      port: 6379
      password: redis123
      database: 0

    nats:
      url: nats://jobs-service:jobs123@nats-client.messaging.svc.cluster.local:4222

    storage:
      type: s3
      endpoint: http://minio.storage.svc.cluster.local:9000
      access_key: zama
      secret_key: zama123
      bucket: job-inputs

    features:
      idempotency_ttl: 86400
      max_job_size: 10485760  # 10MB
      supported_types:
        - fhe_computation
        - proof_generation
        - key_rotation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-submission-service
  namespace: zama-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-submission
      tier: api
  template:
    metadata:
      labels:
        app: job-submission
        tier: api
    spec:
      containers:
      - name: service
        image: zama/job-submission:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: CONFIG_PATH
          value: /etc/config/config.yaml
        - name: LOG_LEVEL
          value: info
        - name: ENVIRONMENT
          value: development
        volumeMounts:
        - name: config
          mountPath: /etc/config
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: job-submission-config
---
apiVersion: v1
kind: Service
metadata:
  name: job-submission-service
  namespace: zama-system
  labels:
    app: job-submission
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: job-submission
---
# Kong Ingress for API Gateway routing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zama-api-v1
  namespace: zama-system
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "true"
    konghq.com/protocols: "http,https"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /v1/jobs
        pathType: Prefix
        backend:
          service:
            name: job-submission-service
            port:
              number: 80