apiVersion: v1
kind: ConfigMap
metadata:
  name: job-processing-config
  namespace: zama-system
data:
  config.yaml: |
    worker:
      concurrency: 10
      queue_name: jobs

    database:
      host: postgres.storage.svc.cluster.local
      port: 5432
      database: zama_jobs
      username: zama
      password: zama123

    nats:
      url: nats://jobs-service:jobs123@nats-client.messaging.svc.cluster.local:4222

    storage:
      input:
        endpoint: http://minio.storage.svc.cluster.local:9000
        access_key: zama
        secret_key: zama123
        bucket: job-inputs
      results:
        endpoint: http://minio.storage.svc.cluster.local:9000
        access_key: zama
        secret_key: zama123
        bucket: job-results

    processing:
      timeout: 3600  # 1 hour
      max_memory: 2Gi
      max_cpu: 2
      retry_attempts: 3

    blockchain:
      service_url: http://blockchain-service.zama-system.svc.cluster.local:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-processing-service
  namespace: zama-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-processing
      tier: worker
  template:
    metadata:
      labels:
        app: job-processing
        tier: worker
    spec:
      containers:
      - name: worker
        image: zama/job-processing:latest
        env:
        - name: CONFIG_PATH
          value: /etc/config/config.yaml
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config
          mountPath: /etc/config
        - name: temp-storage
          mountPath: /tmp/work
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: job-processing-config
      - name: temp-storage
        emptyDir:
          sizeLimit: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: job-processing-service
  namespace: zama-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: job-processing